### ISSUE TITLE
sam 社群 群聊 主要是解决开发的时候不交叉/重复  大家都玩sam 坐下来谈谈  里面有中科院自动化大佬 sam官方git群

### ISSUE THREAD

**Issue by willshion** [jiawen-zhu/HQTrack#2]
![a80cd7d3ec1e2a45863df93a6775d2e](https://github.com/jiawen-zhu/HQTrack/assets/13349979/57b48b72-3ee1-4bff-bdbc-84d038c6d4d2)

**Comment by vero1925** [comment]
二维码今天失效了，可以帮忙拉进群么

**Comment by carry-all-coder** [comment]
二维码失效了，求更新
