### ISSUE TITLE
sam_hq_vit_l.pth model not found error

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [jiawen-zhu/HQTrack#6]
Hello,

I was trying to run the demo.py file but I had the error above, so I figured that in the code it is written as vit_l model which is not shared so I changed it as below :
 
`model_type = 'vit_h'
sam_checkpoint = os.path.join(base_path, '..', 'segment_anything_hq/pretrained_model/sam_hq_vit_h.pth')`

Great job, by the way.

**Comment by jiawen-zhu** [comment]
Hi~ For convenience, we created the demo with a SAM-HQ_vit_l pretrained model. You can easily replace the Mask Refiner model by modifying the settings in demo.py. The pretrained model can be downloaded from [SAM-HQ](https://github.com/SysCV/SAM-HQ).
